repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.1
    hooks:
      - id: gitleaks

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        entry: uvx ruff format
        language: system
        pass_filenames: false
        files: \.py$

      - id: ruff-lint
        name: ruff lint
        entry: uvx ruff check --fix
        language: system
        pass_filenames: false
        files: \.py$

      - id: ty-check
        name: ty type check
        entry: uvx ty check
        language: system
        pass_filenames: false
        files: \.py$
